### PR TITLE
add test: render 3D array

### PR DESCRIPTION
**Pull request by ahaoboy**

### CODE REVIEW

**Comment by yisar** [comment]
good job！

**Comment by mindplay-dk** [comment]
I don't think this adds anything in terms of test-coverage?

There are already tests demonstrating updates of child nodes, and there's no difference between rendering something 2 or 3 or 1000 levels deep.

**Comment by yisar** [comment]
The nesting of arrays is very special. The previous implementation does not support the nesting of arrays. Now it works well and should also add the test cases.
However, we have to admit that the new implementation performance has lost, but it may be optimized.

**Comment by yisar** [comment]
I modified it, and now the array will generate a flattened array in the H function phase.
```js
{Array(2).fill().map((x, i) =>
      Array(2).fill().map((z, j) => (
          <div>
            {i},{j}
          </div>
        )
    )
  )}
```
It will be equal to

```js
{Array(2).fill().map((x, i) =>
        <div>
            {i}
        </div>
    )
  )}
```
This seems to be the normal way. It can reduce the hydration of vdom tree. The disadvantage is that they cannot have the same key.

**Comment by mindplay-dk** [comment]
> now the array will generate a flattened array in the H function phase

Yeah, that makes more sense to me. 🙂👍

> The disadvantage is that they cannot have the same key.

That's also the advantage - if you're building a set of keyed nodes from multiple function-calls, each returning a range of nodes, you don't need to worry about manually unwrapping and combining them into one array.

I think the support for arrays as node-values exists in other frameworks mostly as a convenience - typically, the parent node is what keys relate to; a "parent array" in the input doesn't usually have any real meaning in itself.

**Pull request merged**
