### PR TITLE
upgrade action

### PR DESCRIPTION
**Pull request by wu-yu-xuan**

### CODE REVIEW

**Comment by yisar** [comment]
Will this make the build work faster?

**Comment by wu-yu-xuan** [comment]
will be faster if hit cache

**Comment by yisar** [comment]
Okey, merged!

**Comment by wu-yu-xuan** [comment]
you can see
https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
https://github.com/actions/cache

**Pull request merged**
